---
title: "r-matrices"
author: "Karol Paya"
format: html
editor_options: 
chunk_output_type: console
---

```{r}
# Make a sequence of values from 1 - 10 ----
my_values <- seq(from = 1, to = 10, by = 1)

# Look at it (always) ----
my_values
```

```{r}
# Convert to matrix ----
my_matrix <- matrix(data = my_values,
                    nrow = 2,
                    ncol = 5,
                    byrow = TRUE)

# Check it out ----
(my_matrix)
```
```{r}
#incorrectly declared matrix size
#matrix(data=my_values, nrow=2, ncol=3, byrow=TRUE)
#matrix(data=my_values, nrow=3, ncol=4, byrow=TRUE)
```

##Let's do some math with matrices


```{r}
#Scalar multiplication---
4*my_matrix

#creating a separate matrix
my_values2<-seq(from=21, to=30, by=1)
my_matrix2=matrix(data=my_values2, nrow=2, byrow=TRUE)
my_matrix2
```

```{r}
#Let's add matrices
my_matrix+my_matrix2

#dot product
cats<- matrix(data=c(0,4,3,1),nrow=2, byrow=TRUE)
dogs<-matrix(data=c(6,-3,0,2) , nrow=2, byrow=TRUE)

cats %*% dogs
```

```{r}
#create the matrix
insect_leslie <-matrix(data=c(0,0,600,0.2,0,0,0,0.08,0),nrow=3,byrow=TRUE)

insect_y0<-c(12000,700,500)

#pop at year 1
insect_y1<-insect_leslie %*% insect_y0
insect_y1
```

```{r}
#pop at year 2
insect_y2<-insect_leslie%*% insect_y1
insect_y3<-insect_leslie%*% insect_y2
```



